import pandas as pd

from langchain.tools import tool

from daily_forecasting import (
    load_full_data,
    get_daily_revenue,
    evaluate_model,
    forecast_next_month,
)


# ============================================================
# LOAD PROJECT DATA
# ============================================================

def load_data():
    df = pd.read_csv(
        "data/online_retail.csv"
    )

    df["InvoiceDate"] = pd.to_datetime(
        df["InvoiceDate"]
    )

    df["Revenue"] = (
        df["Quantity"] * df["Price"]
    )

    return df


# ============================================================
# TOOL 1: BUSINESS SUMMARY
# ============================================================

@tool
def get_business_summary() -> dict:
    """Get the main business KPIs from the retail dataset.

    Returns actual values calculated from the project dataset.
    Revenue and prices are in GBP.
    """

    df = load_data()

    return {
        "currency": "GBP",
        "currency_symbol": "£",
        "total_revenue": round(
            float(df["Revenue"].sum()),
            2
        ),
        "total_quantity": int(
            df["Quantity"].sum()
        ),
        "unique_products": int(
            df["Description"].nunique()
        ),
        "unique_customers": int(
            df["Customer ID"].nunique()
        ),
        "unique_countries": int(
            df["Country"].nunique()
        ),
        "total_transactions": int(
            df["Invoice"].nunique()
        ),
    }


# ============================================================
# TOOL 2: TOP PRODUCTS BY REVENUE
# ============================================================

@tool
def get_top_products(
    n: int = 5
) -> dict:
    """Get the top products ranked by total revenue."""

    df = load_data()

    result = (
        df.groupby("Description")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .head(n)
    )

    return {
        "currency": "GBP",
        "products": {
            str(product): round(
                float(revenue),
                2
            )
            for product, revenue in result.items()
        },
    }


# ============================================================
# TOOL 3: LOWEST PRODUCTS BY REVENUE
# ============================================================

@tool
def get_bottom_products(
    n: int = 5
) -> dict:
    """Get products with the lowest total revenue."""

    df = load_data()

    result = (
        df.groupby("Description")["Revenue"]
        .sum()
        .sort_values(ascending=True)
        .head(n)
    )

    return {
        "currency": "GBP",
        "products": {
            str(product): round(
                float(revenue),
                2
            )
            for product, revenue in result.items()
        },
    }


# ============================================================
# TOOL 4: TOP PRODUCTS BY QUANTITY
# ============================================================

@tool
def get_top_products_by_quantity(
    n: int = 5
) -> dict:
    """Get products ranked by total quantity sold."""

    df = load_data()

    result = (
        df.groupby("Description")["Quantity"]
        .sum()
        .sort_values(ascending=False)
        .head(n)
    )

    return {
        "products": {
            str(product): int(quantity)
            for product, quantity in result.items()
        }
    }


# ============================================================
# TOOL 5: REVENUE BY COUNTRY
# ============================================================

@tool
def get_revenue_by_country(
    n: int = 5
) -> dict:
    """Get countries ranked by total revenue."""

    df = load_data()

    result = (
        df.groupby("Country")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .head(n)
    )

    return {
        "currency": "GBP",
        "countries": {
            str(country): round(
                float(revenue),
                2
            )
            for country, revenue in result.items()
        },
    }


# ============================================================
# TOOL 6: SPECIFIC COUNTRY REVENUE
# ============================================================

@tool
def get_country_revenue(
    country: str
) -> dict:
    """Get revenue generated by a specific country."""

    df = load_data()

    matches = df[
        df["Country"]
        .str.lower()
        .str.strip()
        == country.lower().strip()
    ]

    if matches.empty:
        return {
            "error": (
                f"Country '{country}' "
                "was not found."
            )
        }

    revenue = matches["Revenue"].sum()

    return {
        "country": country,
        "currency": "GBP",
        "revenue": round(
            float(revenue),
            2
        ),
        "transactions": int(
            matches["Invoice"].nunique()
        ),
    }


# ============================================================
# TOOL 7: TOP CUSTOMERS
# ============================================================

@tool
def get_top_customers(
    n: int = 5
) -> dict:
    """Get customers ranked by total revenue."""

    df = load_data()

    customer_data = (
        df.dropna(
            subset=["Customer ID"]
        )
    )

    result = (
        customer_data
        .groupby("Customer ID")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .head(n)
    )

    return {
        "currency": "GBP",
        "customers": {
            str(int(customer)): round(
                float(revenue),
                2
            )
            for customer, revenue in result.items()
        },
    }


# ============================================================
# TOOL 8: AVERAGE ORDER VALUE
# ============================================================

@tool
def get_average_order_value() -> dict:
    """Calculate the average revenue per invoice."""

    df = load_data()

    total_revenue = df["Revenue"].sum()

    total_transactions = (
        df["Invoice"].nunique()
    )

    aov = (
        total_revenue
        / total_transactions
    )

    return {
        "currency": "GBP",
        "average_order_value": round(
            float(aov),
            2
        ),
        "total_revenue": round(
            float(total_revenue),
            2
        ),
        "total_transactions": int(
            total_transactions
        ),
    }


# ============================================================
# TOOL 9: MONTHLY REVENUE
# ============================================================

@tool
def get_monthly_revenue() -> dict:
    """Get total revenue for each month."""

    df = load_data()

    result = (
        df.groupby(
            df["InvoiceDate"].dt.to_period("M")
        )["Revenue"]
        .sum()
        .sort_index()
    )

    return {
        str(month): round(
            float(revenue),
            2
        )
        for month, revenue in result.items()
    }


# ============================================================
# TOOL 10: BEST MONTH
# ============================================================

@tool
def get_best_month() -> dict:
    """Find the month with the highest revenue."""

    df = load_data()

    monthly = (
        df.groupby(
            df["InvoiceDate"].dt.to_period("M")
        )["Revenue"]
        .sum()
    )

    best_month = monthly.idxmax()

    return {
        "month": str(best_month),
        "currency": "GBP",
        "revenue": round(
            float(monthly.max()),
            2
        ),
    }


# ============================================================
# TOOL 11: MONTHLY REVENUE GROWTH
# ============================================================

@tool
def get_monthly_growth() -> dict:
    """Calculate month-over-month revenue growth."""

    df = load_data()

    monthly = (
        df.groupby(
            df["InvoiceDate"].dt.to_period("M")
        )["Revenue"]
        .sum()
        .sort_index()
    )

    growth = (
        monthly.pct_change()
        * 100
    )

    return {
        str(month): (
            None
            if pd.isna(value)
            else round(
                float(value),
                2
            )
        )
        for month, value in growth.items()
    }


# ============================================================
# TOOL 12: FINAL NEXT-MONTH FORECAST
# ============================================================

@tool
def get_next_month_forecast() -> dict:
    """Forecast the next calendar month's revenue.

    Uses the daily Random Forest forecasting pipeline
    trained on the full Online Retail II transaction history.

    Evaluation metrics are calculated dynamically.
    Revenue is in GBP.
    """

    # Load full transaction history
    full_df = load_full_data()

    # Convert transactions to daily revenue
    daily_revenue = get_daily_revenue(
        full_df
    )

    # Evaluate model dynamically
    (
        _,
        mae,
        rmse,
        r2
    ) = evaluate_model(
        daily_revenue
    )

    # Forecast next calendar month
    (
        forecast_df,
        month,
        total_forecast
    ) = forecast_next_month(
        daily_revenue
    )

    return {
        "forecast_month": str(month),
        "currency": "GBP",
        "predicted_revenue": round(
            float(total_forecast),
            2
        ),
        "forecasted_days": len(
            forecast_df
        ),
        "model": "Random Forest",
        "granularity": "Daily",
        "mae": round(
            float(mae),
            2
        ),
        "rmse": round(
            float(rmse),
            2
        ),
        "r2": round(
            float(r2),
            2
        ),
    }


# ============================================================
# TEST TOOLS
# ============================================================

if __name__ == "__main__":

    print(
        "===== BUSINESS SUMMARY ====="
    )

    print(
        get_business_summary.invoke({})
    )

    print(
        "\n===== TOP PRODUCTS ====="
    )

    print(
        get_top_products.invoke(
            {"n": 5}
        )
    )

    print(
        "\n===== LOWEST PRODUCTS ====="
    )

    print(
        get_bottom_products.invoke(
            {"n": 5}
        )
    )

    print(
        "\n===== TOP PRODUCTS BY QUANTITY ====="
    )

    print(
        get_top_products_by_quantity.invoke(
            {"n": 5}
        )
    )

    print(
        "\n===== REVENUE BY COUNTRY ====="
    )

    print(
        get_revenue_by_country.invoke(
            {"n": 5}
        )
    )

    print(
        "\n===== GERMANY REVENUE ====="
    )

    print(
        get_country_revenue.invoke(
            {"country": "Germany"}
        )
    )

    print(
        "\n===== TOP CUSTOMERS ====="
    )

    print(
        get_top_customers.invoke(
            {"n": 5}
        )
    )

    print(
        "\n===== AVERAGE ORDER VALUE ====="
    )

    print(
        get_average_order_value.invoke({})
    )

    print(
        "\n===== BEST MONTH ====="
    )

    print(
        get_best_month.invoke({})
    )

    print(
        "\n===== MONTHLY GROWTH ====="
    )

    print(
        get_monthly_growth.invoke({})
    )

    print(
        "\n===== NEXT MONTH FORECAST ====="
    )

    print(
        get_next_month_forecast.invoke({})
    )